#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apache-maven
Version  : 3.6.0
Release  : 23
URL      : http://mirrors.ibiblio.org/apache/maven/maven-3/3.6.0/source/apache-maven-3.6.0-src.tar.gz
Source0  : http://mirrors.ibiblio.org/apache/maven/maven-3/3.6.0/source/apache-maven-3.6.0-src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: apache-maven-bin = %{version}-%{release}
Requires: apache-maven-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : mvn-aether-core
BuildRequires : mvn-animal-sniffer
BuildRequires : mvn-antlr
BuildRequires : mvn-antlr4
BuildRequires : mvn-aopalliance
BuildRequires : mvn-apache
BuildRequires : mvn-apache-jar-resource-bundle
BuildRequires : mvn-apache-rat
BuildRequires : mvn-asm
BuildRequires : mvn-autolink
BuildRequires : mvn-avalon-framework
BuildRequires : mvn-backport-util-concurrent
BuildRequires : mvn-beanshell
BuildRequires : mvn-build-helper-maven-plugin
BuildRequires : mvn-buildnumber-maven-plugin
BuildRequires : mvn-byte-buddy
BuildRequires : mvn-cdi-api
BuildRequires : mvn-checker-compat-qual
BuildRequires : mvn-checkstyle
BuildRequires : mvn-classworlds
BuildRequires : mvn-commons-beanutils
BuildRequires : mvn-commons-chain
BuildRequires : mvn-commons-cli
BuildRequires : mvn-commons-codec
BuildRequires : mvn-commons-collections
BuildRequires : mvn-commons-compress
BuildRequires : mvn-commons-digester
BuildRequires : mvn-commons-httpclient
BuildRequires : mvn-commons-io
BuildRequires : mvn-commons-jxpath
BuildRequires : mvn-commons-lang
BuildRequires : mvn-commons-lang3
BuildRequires : mvn-commons-logging
BuildRequires : mvn-commons-parent
BuildRequires : mvn-commons-validator
BuildRequires : mvn-decentxml
BuildRequires : mvn-dom4j
BuildRequires : mvn-doxia
BuildRequires : mvn-doxia-sitetools
BuildRequires : mvn-doxia-tools
BuildRequires : mvn-enforcer
BuildRequires : mvn-error_prone_annotations
BuildRequires : mvn-extra-enforcer-rules
BuildRequires : mvn-file-management
BuildRequires : mvn-flexmark-java
BuildRequires : mvn-genesis
BuildRequires : mvn-google
BuildRequires : mvn-google-collections
BuildRequires : mvn-guava
BuildRequires : mvn-guice
BuildRequires : mvn-hamcrest
BuildRequires : mvn-httpcomponents-client
BuildRequires : mvn-httpcomponents-core
BuildRequires : mvn-icu4j
BuildRequires : mvn-j2objc-annotations
BuildRequires : mvn-jackrabbit
BuildRequires : mvn-jackson-annotations
BuildRequires : mvn-jackson-core
BuildRequires : mvn-jackson-databind
BuildRequires : mvn-jansi
BuildRequires : mvn-java-boot-classpath-detector
BuildRequires : mvn-javax-servlet
BuildRequires : mvn-javax.inject
BuildRequires : mvn-jdom
BuildRequires : mvn-jetty
BuildRequires : mvn-jetty-parent
BuildRequires : mvn-jetty-util
BuildRequires : mvn-jna
BuildRequires : mvn-jsch
BuildRequires : mvn-jsch.agentproxy.connector-factory
BuildRequires : mvn-jsch.agentproxy.core
BuildRequires : mvn-jsch.agentproxy.pageant
BuildRequires : mvn-jsch.agentproxy.sshagent
BuildRequires : mvn-jsch.agentproxy.svnkit-trilead-ssh2
BuildRequires : mvn-jsch.agentproxy.usocket-jna
BuildRequires : mvn-jsch.agentproxy.usocket-nc
BuildRequires : mvn-jsoup
BuildRequires : mvn-jsr250-api
BuildRequires : mvn-jsr305
BuildRequires : mvn-junit
BuildRequires : mvn-log4j
BuildRequires : mvn-logback-classic
BuildRequires : mvn-logback-core
BuildRequires : mvn-logkit
BuildRequires : mvn-maven
BuildRequires : mvn-maven-aether-provider
BuildRequires : mvn-maven-archiver
BuildRequires : mvn-maven-artifact
BuildRequires : mvn-maven-artifact-manager
BuildRequires : mvn-maven-builder-support
BuildRequires : mvn-maven-bundle-plugin
BuildRequires : mvn-maven-compat
BuildRequires : mvn-maven-core
BuildRequires : mvn-maven-embedder
BuildRequires : mvn-maven-error-diagnostics
BuildRequires : mvn-maven-model
BuildRequires : mvn-maven-model-builder
BuildRequires : mvn-maven-monitor
BuildRequires : mvn-maven-parent
BuildRequires : mvn-maven-plugin-api
BuildRequires : mvn-maven-plugin-descriptor
BuildRequires : mvn-maven-plugin-parameter-documenter
BuildRequires : mvn-maven-plugin-registry
BuildRequires : mvn-maven-plugin-testing
BuildRequires : mvn-maven-plugin-tools
BuildRequires : mvn-maven-profile
BuildRequires : mvn-maven-project
BuildRequires : mvn-maven-reporting-api
BuildRequires : mvn-maven-reporting-exec
BuildRequires : mvn-maven-reporting-impl
BuildRequires : mvn-maven-repository-metadata
BuildRequires : mvn-maven-resolver
BuildRequires : mvn-maven-scm
BuildRequires : mvn-maven-scm-provider-svnjava
BuildRequires : mvn-maven-settings
BuildRequires : mvn-maven-shared
BuildRequires : mvn-maven-slf4j-provider
BuildRequires : mvn-maven-surefire
BuildRequires : mvn-maven-toolchain
BuildRequires : mvn-mockito-core
BuildRequires : mvn-modello
BuildRequires : mvn-mojo-parent
BuildRequires : mvn-mojo-signature
BuildRequires : mvn-mvnplugins
BuildRequires : mvn-nekohtml
BuildRequires : mvn-objenesis
BuildRequires : mvn-openhtmltopdf-parent
BuildRequires : mvn-org.eclipse.sisu.inject
BuildRequires : mvn-org.eclipse.sisu.plexus
BuildRequires : mvn-oro
BuildRequires : mvn-oss-parents
BuildRequires : mvn-ow2
BuildRequires : mvn-pdfbox
BuildRequires : mvn-plexus
BuildRequires : mvn-plexus-archiver
BuildRequires : mvn-plexus-build-api
BuildRequires : mvn-plexus-cipher
BuildRequires : mvn-plexus-classworlds
BuildRequires : mvn-plexus-cli
BuildRequires : mvn-plexus-compiler
BuildRequires : mvn-plexus-containers
BuildRequires : mvn-plexus-i18n
BuildRequires : mvn-plexus-interactivity
BuildRequires : mvn-plexus-interpolation
BuildRequires : mvn-plexus-io
BuildRequires : mvn-plexus-languages
BuildRequires : mvn-plexus-resources
BuildRequires : mvn-plexus-utils
BuildRequires : mvn-plexus-velocity
BuildRequires : mvn-qdox
BuildRequires : mvn-sequence-library
BuildRequires : mvn-servlet-api
BuildRequires : mvn-sisu
BuildRequires : mvn-sisu-maven-plugin
BuildRequires : mvn-slf4j
BuildRequires : mvn-snakeyaml
BuildRequires : mvn-snappy
BuildRequires : mvn-sonatype-aether
BuildRequires : mvn-sonatype-plexus-sec-dispatcher
BuildRequires : mvn-sqljet
BuildRequires : mvn-sslext
BuildRequires : mvn-struts
BuildRequires : mvn-svnkit
BuildRequires : mvn-trilead-ssh2
BuildRequires : mvn-tycho
BuildRequires : mvn-velocity
BuildRequires : mvn-velocity-tools
BuildRequires : mvn-wagon
BuildRequires : mvn-weld-api
BuildRequires : mvn-weld-parent
BuildRequires : mvn-xbean
BuildRequires : mvn-xercesImpl
BuildRequires : mvn-xercesMinimal
BuildRequires : mvn-xml-apis
BuildRequires : mvn-xmlunit
BuildRequires : mvn-xmlunit-core
BuildRequires : mvn-xz
BuildRequires : openjdk
BuildRequires : openjdk-dev
Patch1: maven-script.patch

%description
<!---
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

%package bin
Summary: bin components for the apache-maven package.
Group: Binaries
Requires: apache-maven-data = %{version}-%{release}

%description bin
bin components for the apache-maven package.


%package data
Summary: data components for the apache-maven package.
Group: Data

%description data
data components for the apache-maven package.


%prep
%setup -q -n apache-maven-3.6.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
mkdir %{buildroot}
cp -r /usr/share/java/.m2 %{buildroot}/.m2
mvn --offline -Dmaven.repo.local=%{buildroot}/.m2/repository install -Drat.skip=true -Dplatform=linux64 --fail-at-end

%install

## install_append content
mkdir -p %{buildroot}/usr/share/apache-maven
tar -xf apache-maven/target/apache-maven-3.6.0-bin.tar.gz -C %{buildroot}/usr/share/apache-maven --strip-components=1
mkdir -p %{buildroot}/usr/bin
for cmd in mvnDebug mvnyjp; do
sed s/@@CMD@@/$cmd/ maven-script >%{buildroot}/usr/bin/$cmd
chmod +x %{buildroot}/usr/bin/$cmd
done
sed s/@@CMD@@/mvn/ maven-script >%{buildroot}/usr/share/apache-maven/bin/mvn-script
ln -sf ../share/apache-maven/bin/mvn-script %{buildroot}/usr/bin/mvn
chmod +x %{buildroot}/usr/share/apache-maven/bin/mvn-script
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mvn
/usr/bin/mvnDebug
/usr/bin/mvnyjp

%files data
%defattr(-,root,root,-)
%exclude /usr/share/apache-maven/lib/jansi-native/freebsd32/libjansi.so
%exclude /usr/share/apache-maven/lib/jansi-native/freebsd64/libjansi.so
%exclude /usr/share/apache-maven/lib/jansi-native/linux32/libjansi.so
%exclude /usr/share/apache-maven/lib/jansi-native/osx/libjansi.jnilib
%exclude /usr/share/apache-maven/lib/jansi-native/windows32/jansi.dll
%exclude /usr/share/apache-maven/lib/jansi-native/windows64/jansi.dll
/usr/share/apache-maven/LICENSE
/usr/share/apache-maven/NOTICE
/usr/share/apache-maven/README.txt
/usr/share/apache-maven/bin/m2.conf
/usr/share/apache-maven/bin/mvn
/usr/share/apache-maven/bin/mvn-script
/usr/share/apache-maven/bin/mvn.cmd
/usr/share/apache-maven/bin/mvnDebug
/usr/share/apache-maven/bin/mvnDebug.cmd
/usr/share/apache-maven/bin/mvnyjp
/usr/share/apache-maven/boot/plexus-classworlds-2.5.2.jar
/usr/share/apache-maven/conf/logging/simplelogger.properties
/usr/share/apache-maven/conf/settings.xml
/usr/share/apache-maven/conf/toolchains.xml
/usr/share/apache-maven/lib/animal-sniffer-annotations-1.14.jar
/usr/share/apache-maven/lib/animal-sniffer-annotations.license
/usr/share/apache-maven/lib/aopalliance-1.0.jar
/usr/share/apache-maven/lib/cdi-api-1.0.jar
/usr/share/apache-maven/lib/checker-compat-qual-2.0.0.jar
/usr/share/apache-maven/lib/checker-compat-qual.license
/usr/share/apache-maven/lib/commons-cli-1.4.jar
/usr/share/apache-maven/lib/commons-io-2.5.jar
/usr/share/apache-maven/lib/commons-lang3-3.8.1.jar
/usr/share/apache-maven/lib/error_prone_annotations-2.1.3.jar
/usr/share/apache-maven/lib/ext/README.txt
/usr/share/apache-maven/lib/guava-25.1-android.jar
/usr/share/apache-maven/lib/guice-4.2.1-no_aop.jar
/usr/share/apache-maven/lib/j2objc-annotations-1.1.jar
/usr/share/apache-maven/lib/jansi-1.17.1.jar
/usr/share/apache-maven/lib/jansi-native/README.txt
/usr/share/apache-maven/lib/jansi-native/linux64/libjansi.so
/usr/share/apache-maven/lib/javax.inject-1.jar
/usr/share/apache-maven/lib/jcl-over-slf4j-1.7.25.jar
/usr/share/apache-maven/lib/jcl-over-slf4j.license
/usr/share/apache-maven/lib/jsr250-api-1.0.jar
/usr/share/apache-maven/lib/jsr250-api.license
/usr/share/apache-maven/lib/jsr305-3.0.2.jar
/usr/share/apache-maven/lib/maven-artifact-3.6.0.jar
/usr/share/apache-maven/lib/maven-builder-support-3.6.0.jar
/usr/share/apache-maven/lib/maven-compat-3.6.0.jar
/usr/share/apache-maven/lib/maven-core-3.6.0.jar
/usr/share/apache-maven/lib/maven-embedder-3.6.0.jar
/usr/share/apache-maven/lib/maven-model-3.6.0.jar
/usr/share/apache-maven/lib/maven-model-builder-3.6.0.jar
/usr/share/apache-maven/lib/maven-plugin-api-3.6.0.jar
/usr/share/apache-maven/lib/maven-repository-metadata-3.6.0.jar
/usr/share/apache-maven/lib/maven-resolver-api-1.3.1.jar
/usr/share/apache-maven/lib/maven-resolver-connector-basic-1.3.1.jar
/usr/share/apache-maven/lib/maven-resolver-impl-1.3.1.jar
/usr/share/apache-maven/lib/maven-resolver-provider-3.6.0.jar
/usr/share/apache-maven/lib/maven-resolver-spi-1.3.1.jar
/usr/share/apache-maven/lib/maven-resolver-transport-wagon-1.3.1.jar
/usr/share/apache-maven/lib/maven-resolver-util-1.3.1.jar
/usr/share/apache-maven/lib/maven-settings-3.6.0.jar
/usr/share/apache-maven/lib/maven-settings-builder-3.6.0.jar
/usr/share/apache-maven/lib/maven-shared-utils-3.2.1.jar
/usr/share/apache-maven/lib/maven-slf4j-provider-3.6.0.jar
/usr/share/apache-maven/lib/org.eclipse.sisu.inject-0.3.3.jar
/usr/share/apache-maven/lib/org.eclipse.sisu.inject.license
/usr/share/apache-maven/lib/org.eclipse.sisu.plexus-0.3.3.jar
/usr/share/apache-maven/lib/org.eclipse.sisu.plexus.license
/usr/share/apache-maven/lib/plexus-cipher-1.7.jar
/usr/share/apache-maven/lib/plexus-component-annotations-1.7.1.jar
/usr/share/apache-maven/lib/plexus-interpolation-1.25.jar
/usr/share/apache-maven/lib/plexus-sec-dispatcher-1.4.jar
/usr/share/apache-maven/lib/plexus-utils-3.1.0.jar
/usr/share/apache-maven/lib/slf4j-api-1.7.25.jar
/usr/share/apache-maven/lib/slf4j-api.license
/usr/share/apache-maven/lib/wagon-file-3.2.0.jar
/usr/share/apache-maven/lib/wagon-http-3.2.0-shaded.jar
/usr/share/apache-maven/lib/wagon-provider-api-3.2.0.jar
